name: Get Pocket Highlights

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  recover-pocket-highlights:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: notes-scrapper-scripts
    steps:
      - uses: actions/checkout@v2
        with:
          repository: fabioluciano/notes-scrapper
          path: notes-scrapper-scripts
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: node pocket/index.js
