name: Get Pocket Highlights

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  recover-pocket-highlights:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: fabioluciano/notes-scrapper
          path: notes-scrapper-scripts
      - run: npm install
        working-directory: notes-scrapper-scripts
      - run: node pocket/index.js
        working-directory: notes-scrapper-scripts
        env:
          GETPOCKET_USERNAME: ${{ secrets.GETPOCKET_USERNAME}}
          GETPOCKET_PASSWORD: ${{ secrets.GETPOCKET_PASSWORD}}
      - uses: EndBug/add-and-commit@v7
        with:
          message: "ci: Sync Pocket highlights"
