name: Get Pocket Highlights

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  recover-pocket-highlights:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: notes-scrapper-scripts
    steps:
      - uses: actions/checkout@v2
        with:
          repository: fabioluciano/notes-scrapper
          path: notes-scrapper-scripts
      - run: npm install
        working-directory: notes-scrapper-scripts
      - run: node pocket/index.js
        working-directory: notes-scrapper-scripts
        env:
          GETPOCKET_USERNAME: ${{ secrets.GETPOCKET_USERNAME}}
          GETPOCKET_PASSWORD: ${{ secrets.GETPOCKET_PASSWORD}}
